project:
  type: website

website:
  title: "msdial4tutorial-ja"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - chapter1.qmd
      - chapter2.qmd
      - chapter3.qmd
      - chapter4.qmd
      - chapter5.qmd
      - chapter6.qmd
      - chapter7.qmd
      - chapter8.qmd
      - chapter9.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
